---
Standards:

  -
    Title: Internship Timeline & Companies
    Description: One stop shop for all things internship
    UID: 92b1dbed-3f9a-476d-87ae-855297f26ecd    
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cb20e392-9f72-4402-98dc-5a18632082f5  
        Path: /timeline.md 
  -
    Title: Company Engagement Overview
    Description: Slides & recording
    UID: f9e48962-f37c-4c66-b005-41e59a9cb3ff   
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 9f32e1d7-4cda-4955-a789-79c36d9be1b5   
        Path: /companyengagement.md 
