---
Standards:
  -
    Title: Overview of Mock Interviews
    Description: "General information about the who, what, where, when for mock interviews"
    UID: c59c4618-d53d-4838-b995-b9648895799b
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 70b7da3b-8a4d-4071-a468-44240776d2df
        Path: /overview-of-mock-interviews/overview-of-mock-interviews.md
  -
    Title: Timeline & Companies
    Description: One stop shop for all things internship
    UID: 92b1dbed-3f9a-476d-87ae-855297f26ecd    
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cb20e392-9f72-4402-98dc-5a18632082f5  
        Path: /timeline.md 
  -
    Title: Company Engagement
    Description: Overview presentation
    UID: f9e48962-f37c-4c66-b005-41e59a9cb3ff   
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 9f32e1d7-4cda-4955-a789-79c36d9be1b5   
        Path: /company-engagement/overview.md 
 
  -
    Title: Networking, resumes/bios
    Description: Prepping for Company Engagement
    UID: 94ec9ff3-94f9-4880-9a46-99a3cd15b809    
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 74ae4f13-243e-4945-82b4-fbbbbb00fca3   
        Path: /networking/overview.md 

  -
    Title: Company Presentations
    Description: Presentation recordings
    UID: d6324a20-9309-4e37-93dd-61e1d3520da7    
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: f27621e4-37cb-4814-a593-049fd071de00    
        Path: /company-engagement/rock-pres.md 

      -
        Type: Lesson
        UID: b6e1431b-3bde-4d2a-96f8-22e818644d2f    
        Path: /company-engagement/paper-pres.md 
        
      -
        Type: Lesson
        UID: 92c09f37-d935-418c-91c1-6b444edc3b0d    
        Path: /company-engagement/scissors-pres.md 

  -
    Title: The Interview Process
    Description: "The Interview Process, How to approach interviews"
    UID: 7f3b402c-d1f6-44d3-9ced-935e63b72b29
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: c9046bbf-7f2b-4441-9e8c-c29374265333
        Path: /interview-process/interview-introduction.md
      -
        Type: Lesson
        UID: 3c192ac0-6a5b-492a-9550-8bf503322571
        Path: /interview-process/how-to-interview.md
      -
        Type: Lesson
        UID: db9dd27d-4bbd-4a4b-b52d-f86aed909de8
        Path: /interview-process/interview-recording.md
      -
        Type: Lesson
        UID: 1c4de8b5-215d-47b4-81d4-22d808e1dc11
        Path: /interview-process/sample-questions.md    
  -
    Title: Interview Week
    Description: Overview
    UID: 9007aad6-4b21-4373-a640-7c2af4da92ae     
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 682636b7-fe22-40a0-bad2-e69cb0db573f     
        Path: /interview-week/overview.md 
        
      -  
        Type: Lesson
        UID: ce0384ca-f6e4-4113-83b6-b063a076c8b2     
        Path: /interview-week/final-details.md      
  -
    Title: Internship
    Description: Overview
    UID: 0fc6503c-22c2-446c-88a9-6d573db497c8      
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: d94f2bd0-d4fe-4f69-b35a-eb25fb50853c     
        Path: /internship/internship-overview.md 
 
