---
Standards:

  -
    Title: Internship Process
    Description: Introductory Material for Internship Process
    UID: af46cafc-d756-47c9-bc2c-9a4515294cee    
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 607d61e5-f162-4919-a5f4-45f93bad4f9f  
        Path: /internship-process.md 
  
